# Generated by Django 5.2.5 on 2025-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovFlowApp', '0002_remove_document_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Returned', 'Returned'), ('Archived', 'Archived')], default='Pending', max_length=20),
        ),
    ]
