# Generated by Django 5.2.5 on 2025-12-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovFlowApp', '0003_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenthistory',
            name='action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded'), ('Received', 'Received'), ('Returned', 'Returned')], max_length=20),
        ),
    ]
