# Generated by Django 5.2.5 on 2026-03-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GovFlowApp', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Received', 'Received'), ('Returned', 'Returned'), ('Archived', 'Archived'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded'), ('Received', 'Received'), ('Returned', 'Returned'), ('Archived', 'Archived'), ('Completed', 'Completed'), ('Status Update', 'Status Update')], max_length=20),
        ),
    ]
